/* eslint-disable */
// @generated by protobuf-ts 2.8.2 with parameter server_generic,client_grpc1,eslint_disable,ts_nocheck
// @generated from protobuf file "system.proto" (syntax proto3)
// tslint:disable
// @ts-nocheck
import { JumpgateOpeningResponse } from "./system";
import { JumpgateOpening } from "./system";
import { ChatMessage } from "./system";
import { Empty } from "./system";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service SystemServer
 */
export interface ISystemServer<T = ServerCallContext> {
    /**
     * @generated from protobuf rpc: Ping(Empty) returns (Empty);
     */
    ping(request: Empty, context: T): Promise<Empty>;
    /**
     * @generated from protobuf rpc: SendChatMessage(ChatMessage) returns (Empty);
     */
    sendChatMessage(request: ChatMessage, context: T): Promise<Empty>;
    /**
     * @generated from protobuf rpc: OpenJumpgate(JumpgateOpening) returns (JumpgateOpeningResponse);
     */
    openJumpgate(request: JumpgateOpening, context: T): Promise<JumpgateOpeningResponse>;
}
